caddy_version: v2.0.0-beta.17
caddy_filename_prefix: caddy2_beta17
# sha256 checksums for github-released binaries
checksums:
  amd64: b25d0b19fcc9e2d9a6c3009cc086256535cdd8ddea14b09266f8d93d087b88cb
  arm64v8: faddaf4f812c1ca7347bf74430baf04e8dc1e1a548111f153d3a51d1cc527595
# configuration for the stackbrew.tmpl template
variants:
  - dir: alpine
    tags: [ "{{.conf.caddy_version}}", "{{.conf.caddy_version}}-alpine", "alpine", "latest" ]
    architectures: [ amd64 ]
  # Drop this for now!
  # - dir: scratch
  #   tags: [ "{{.conf.caddy_version}}-slim", "scratch" ]
  #   architectures: [ amd64 ]
  - dir: builder
    tags: [ "{{.conf.caddy_version}}-builder", "builder" ]
    architectures: [ amd64 ]
