caddy_version: v2.0.0-beta.15
# configuration for the stackbrew.tmpl template
variants:
  - dir: alpine
    tags: [ "{{.conf.caddy_version}}", "{{.conf.caddy_version}}-alpine", "alpine", "latest" ]
    architectures: [ amd64 ]
  - dir: scratch
    tags: [ "{{.conf.caddy_version}}-slim", "scratch" ]
    architectures: [ amd64 ]
  - dir: builder
    tags: [ "{{.conf.caddy_version}}-builder", "builder" ]
    architectures: [ amd64 ]
